language: node_js

node_js:
  - "10"

branches:
  only:
    - master

jobs:
  include:
    - install: npm ci
      env: USING_PACKAGE_LOCK=true
      cache: npm
    - install: npm install
      before_install: rm package-lock.json
      env: USING_PACKAGE_LOCK=false
      cache: false

before_script:
  - npm ls --depth=0
